### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by willococa** [lincoln1883/my-portfolio-website#4]
- Please, try to use grid-autocolumns in the .works-cards styles for a better layout
- I kindly suggest to follow the mobile first procedure as specified in the requirement here:
  https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/1_setup.md that states to set the minimum mobile screen  of 375px and here:
 https://www.mightyminnow.com/2013/11/what-is-mobile-first-css-and-why-does-it-rock/ in the section "How do I code mobile first"

**Comment by lincoln1883** [comment]
all done.
